dist: xenial
sudo: true
language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential cmake
  - sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libgoogle-glog-dev
  - sudo apt-get install python3 python3-pip

install:
  - pip3 install -r requirements.txt
  - pip3 install -e .

# command to run tests
script:
  - pytest ./hiq/projectq/backends/_sim/_simulator_mpi_test.py 
  - pytest ./hiq/projectq/backends/_sim/_stabilizer_simulator_test.py
  - python3 examples/BV_algorithm_constant_mpi.py
  - python3 examples/exactgrover_mpi.py
  - python3 examples/grover_mpi.py
  - python3 examples/maximum_search_constant_mpi.py
  - python3 examples/phase_estimation_mpi.py
  - python3 examples/qecc9_sta.py
  - python3 examples/SymMatrixSolver_mpi.py
  - python3 examples/teleport_mpi.py
  - python3 examples/ToeplitzSimplify_constant.py
  - python3 examples/grover_mpi.py
  - python3 examples/unknown_num_search_constant_mpi.py
